---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart systemd-hostnamed
  service:
    name: systemd-hostnamed
    state: restarted

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted

- name: restart ufw
  ufw: state=reloaded

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart unbound
  service:
    name: unbound
    state: restarted

- name: restart maldet
  service:
    name: maldet
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
