# This is the top-level playbook for rebooting a server, decrypting the encfs
# filesystem, and restarting all processes dependent on the filesystem.

- hosts: remote
  remote_user: deploy
  become: True
  gather_facts: True
  vars_prompt:
    - name: "confirmation"
      prompt: "Do you want to reboot the server? Answer with 'yes'"
      default: "no"
      private: no

  roles:
    - { role: reboot, tags: reboot }
