---
# This is the top-level playbook for a remote server server

- hosts: remote
  remote_user: deploy
  become: True
  gather_facts: True

  roles:
    - { role: common, tags: common }
    - { role: remote, tags: remote }
    - { role: mailserver, tags: mailserver }
    - { role: webmail, tags: webmail }
    - { role: nextcloud, tags: nextcloud }
    - { role: blog, tags: blog }
    - { role: ircbouncer, tags: ircbouncer }
    - { role: xmpp, tags: xmpp }
    - { role: vpn, tags: vpn }
    - { role: news, tags: news }
    - { role: git, tags: git }
    - { role: readlater, tags: readlater }
    - { role: tarsnap, tags: tarsnap }
    - { role: monitoring, tags: monitoring }
