---
# This is the top-level playbook for a local computer

- hosts: all
  gather_facts: False
  tasks:
    - name: Check for single host being run
      fail: msg="Single host check failed. Use '-l hostname'"
      when: "{{ play_hosts | length }} != 1"

- hosts: local
  become: True
  gather_facts: True

  roles:
    - { role: common, tags: common }

- hosts: home
  remote_user: deploy
  become: True
  gather_facts: True

  roles:
    - { role: common, tags: common }

- hosts: remote
  remote_user: deploy
  become: True
  gather_facts: True
  vars_prompt:
    - name: "confirmation"
      prompt: "Do you want to reboot the server after initial setup? Answer with 'yes'"
      default: "no"
      private: no

  roles:
    - { role: common, tags: common }
    - { role: remote, tags: remote }
    - { role: mailserver, tags: mailserver }
    - { role: webmail, tags: webmail }
    - { role: blog, tags: blog }
    - { role: ircbouncer, tags: ircbouncer }
    - { role: xmpp, tags: xmpp }
    - { role: nextcloud, tags: nextcloud }
    - { role: vpn, tags: vpn }
    - { role: tarsnap, tags: tarsnap }
    - { role: news, tags: news }
    - { role: git, tags: git }
    - { role: readlater, tags: readlater }
    - { role: monitoring, tags: monitoring } # Monitoring role should be last. See roles/monitoring/README.md
