- name: Install Postfix and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libsasl2-modules
    - postfix
    - postfix-pcre
    - postfix-pgsql
    - postgrey
    - python-psycopg2
    - sasl2-bin
  tags:
    - dependencies

- name: Remove existing mail transfer agent
  apt: pkg={{ item }} state=absent purge=yes
  with_items:
    - exim4
    - exim4-base
    - exim4-config
    - exim4-daemon-light
  tags:
    - dependencies

- name: Get public IP
  ipify_facts:

- name: Create database user for mail server
  postgresql_user: login_host=127.0.0.1 login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ mail_db_username }} password="{{ mail_db_password }}" encrypted=yes state=present
  notify: import sql postfix
  no_log: True

- name: Create database for mail server
  postgresql_db: login_host=127.0.0.1 login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ mail_db_database }} state=present owner={{ mail_db_username }}
  notify: import sql postfix
  no_log: True

- name: Copy import.sql
  template: src=etc_postfix_import.sql.j2 dest=/etc/postfix/import.sql owner=root group=root mode=0600
  notify: import sql postfix

- name: Create postfix maps directory
  file: path=/etc/postfix/maps state=directory owner=root group=root
  when: mail_header_privacy == 1

- name: Copy smtp_header_checks.pcre
  template: src=etc_postfix_maps_smtp_header_checks.pcre.j2 dest=/etc/postfix/maps/smtp_header_checks.pcre owner=root group=root
  when: mail_header_privacy == 1

- name: Copy main.cf
  template: src=etc_postfix_main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root
  notify: restart postfix

- name: Copy master.cf
  copy: src=etc_postfix_master.cf dest=/etc/postfix/master.cf owner=root group=root
  notify: restart postfix

- name: Copy additional postfix configuration files
  template: src=etc_postfix_{{ item }}.j2 dest=/etc/postfix/{{ item }} owner=root group=root
  with_items:
    - pgsql-virtual-alias-maps.cf
    - pgsql-virtual-mailbox-domains.cf
    - pgsql-virtual-mailbox-maps.cf
  notify: restart postfix

- name: Set firewall rules for postfix
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - smtp
    - ssmtp
    - submission
  tags: ufw
  notify: restart ufw

- name: Copy fail2ban configuration into place
  copy: src=etc_fail2ban_jail.d_postfix.conf dest=/etc/fail2ban/jail.d/postfix.conf
  notify: restart fail2ban
