---
# Installs and configures the Rspamd spam filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=https://rspamd.com/apt-stable/gpg.key state=present
  tags:
    - dependencies

- name: Add Rspamd repository
  apt_repository: repo="deb https://rspamd.com/apt-stable/ sid main"
  tags:
    - dependencies

- name: Install Rspamd, Rmilter, and Redis
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - rspamd
    - rmilter
    - redis-server
  tags:
    - dependencies

- name: Configure rmilter.common
  copy: src=etc_rmilter.conf.common dest=/etc/rmilter.conf.common
  notify: restart rmilter

- name: Configure rmilter socket
  lineinfile: dest=/etc/rmilter.conf regexp=^bind_socket line="bind_socket = inet:9900@127.0.0.1"
  notify: restart rmilter

- name: Configure rmilter service
  copy: src=lib_systemd_system_rmilter.socket dest=/lib/systemd/system/rmilter.socket
  notify: restart rmilter

- name: Make redis.conf more secure
  file: path=/etc/redis/redis.conf mode=0600 owner=redis

- name: Make redis folder more secure
  file: path=/var/lib/redis owner=redis group=redis mode=0700 recurse=yes

- name: Make sure redis, rspamd, and rmilter are started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - redis-server
    - rspamd
    - rmilter
