# Variables used in multiple roles.

domain: "{{ vault_domain }}"
main_user_name: "{{ vault_main_user_name }}"
admin_email: "{{ main_user_name }}@{{ domain }}"
common_timezone: 'Etc/UTC'
friendly_networks:
  - ""
# - "10.16.100.0/24"
# - "example.com"

db_admin_username: 'postgres'
# db_admin_password: "{{ lookup('password', secret + '/' + 'db_admin_password', length=32) }}"
db_admin_password: "{{ vault_db_admin_password }}"
mysql_admin_password: "{{ vault_mysql_admin_password }}"
