---
# Installs the nextcloud personal cloud software.

- name: Install nextcloud dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - libapache2-mod-php7.0
    - python-psycopg2
    - php7.0-gd
    - php7.0-json
    - php7.0-pgsql
    - php7.0-curl
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-mcrypt
    - php-imagick
    - php7.0-xml
    - php7.0-zip
    - php7.0-fileinfo
    - php7.0-bz2
    - php7.0-openssl
    - ffmpeg
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes

- name: Create database user for nextcloud
  postgresql_user: login_host=127.0.0.1 login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ nextcloud_db_username }} password="{{ nextcloud_db_password }}" role_attr_flags=CREATEDB state=present

- name: Download Nextcloud source
  get_url:
    url="https://download.nextcloud.com/server/releases/nextcloud-11.0.3.tar.bz2"
    dest="/root/nextcloud-11.0.3.tar.bz2"
    sha256sum=28d5ee39f31c6be20f037ad2eb300272ad9bb72a7d428eb0152c7a3fde87d545

- name: Extract Nextcloud into location
  unarchive: src=/root/nextcloud-11.0.3.tar.bz2 dest=/var/www/nextcloud creates=/var/www/nextcloud remote_src=yes

- name: Remove downloaded installation file
  file: path=/root/nextcloud-11.0.3.tar.bz2 state=absent

- name: Ensure correct Nextcloud directory ownership
  file: state=directory path=/var/www/nextcloud owner=www-data group=www-data recurse=yes

- name: Move nextcloud data to encrypted filesystem
  command: mv /var/www/nextcloud/data /decrypted/nextcloud-data creates=/decrypted/nextcloud-data
- file: src=/decrypted/nextcloud-data dest=/var/www/nextcloud/data owner=www-data group=www-data state=link

- name: Make sure apache modules are loaded
  apache2_module:
    state: present
    name:
      - rewrite
      - headers
      - env
      - dir
      - mime
  notify: restart apache

- name: Configure Apache for nextcloud
  template: src=etc_apache2_sites-available_nextcloud.j2 dest=/etc/apache2/sites-available/nextcloud.conf group=root
  notify: restart apache

- name: Enable nextcloud site
  command: a2ensite nextcloud.conf creates=/etc/apache2/sites-enabled/nextcloud.conf
  notify: restart apache

- name: Install nextcloud cronjob
  cron: name="nextcloud" user="www-data" minute="*/15" job="php -f /var/www/nextcloud/cron.php > /dev/null"

# - name: Configure nextcloud
#  command: sudo -u www-data php occ maintenance:install --database \"pgsql\" --database-name \"nextcloud\" --database-user \"{{ nextcloud_db_username }}\" --database-pass \"{{ nextcloud_db_password }}\" --admin-user \"{{ main_user_name }}\" --admin-pass \"{{ nextcloud_user_password }}\"
