---
# Installs the nextcloud personal cloud software.

- name: Install nextcloud dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - libapache2-mod-php7.0
    - php7.0
    - php7.0-apcu
    - php7.0-bz2
    - php7.0-curl
    - php7.0-gd
    - php7.0-intl
    - php-imagick
    - php7.0-json
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-pgsql
    - php7.0-xml
    - php7.0-zip
    - ffmpeg
    - python-psycopg2
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
  no_log: True

- name: Create database user for nextcloud
  postgresql_user: login_host=127.0.0.1 login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ nextcloud_db_username }} password="{{ nextcloud_db_password }}" role_attr_flags=CREATEDB state=present
  no_log: True

- name: Download Nextcloud source
  get_url:
    url="https://download.nextcloud.com/server/releases/nextcloud-11.0.3.tar.bz2"
    dest="/root/nextcloud-11.0.3.tar.bz2"
    sha256sum=28d5ee39f31c6be20f037ad2eb300272ad9bb72a7d428eb0152c7a3fde87d545

- name: Extract Nextcloud into location
  unarchive: src=/root/nextcloud-11.0.3.tar.bz2 dest=/var/www remote_src=yes creates=/var/www/nextcloud/index.html

- name: Remove downloaded installation file
  file: path=/root/nextcloud-11.0.3.tar.bz2 state=absent

- name: Ensure correct Nextcloud directory ownership
  file: state=directory path=/var/www/nextcloud owner=www-data group=www-data recurse=yes

- name: Create Nextcloud data directory
  file: state=directory path=/decrypted/nextcloud-data owner=www-data group=www-data

- name: Disable PHP5 as it conflicts with PHP7.0
  command: a2dismod php5 removes=/etc/apache2/mods-enabled/php5.conf

- name: Make sure required apache modules are loaded
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.conf
  with_items:
    - php7.0
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart apache

- name: Configure Apache for nextcloud
  template: src=etc_apache2_sites-available_nextcloud.j2 dest=/etc/apache2/sites-available/nextcloud.conf group=root
  notify: restart apache

- name: Enable nextcloud site
  command: a2ensite nextcloud.conf creates=/etc/apache2/sites-enabled/nextcloud.conf
  notify: restart apache

- name: Install nextcloud cronjob
  cron: name="nextcloud" user="www-data" minute="*/15" job="php -f /var/www/nextcloud/cron.php > /dev/null"

- name: Copy fail2ban configurations into place
  copy: src={{ item.src }} dest={{ item.dest }} group=root owner=root
  with_items:
  - { src: 'etc_fail2ban_filter.d_nextcloud.conf', dest: '/etc/fail2ban/filter.d/nextcloud.conf' }
  - { src: 'etc_fail2ban_jail.d_nextcloud.conf', dest: '/etc/fail2ban/jail.d/nextcloud.conf' }
  notify: restart fail2ban

- name: Configure nextcloud
  command: php occ maintenance:install
    --database "pgsql"
    --database-name "nextcloud"
    --database-user "{{ nextcloud_db_username }}"
    --database-pass "{{ nextcloud_db_password }}"
    --admin-user "{{ main_user_name }}"
    --admin-pass "{{ nextcloud_user_password }}"
    --data-dir "/decrypted/nextcloud-data"
  become: yes
  become_user: www-data
  args:
    chdir: /var/www/nextcloud
    creates: /decrypted/nextcloud-data/{{ main_user_name }}
  notify: restart apache
  no_log: True

- name: Set admin email
  command: php occ user:setting {{ main_user_name }} settings email "{{ main_user_name }}@{{ domain }}"
  become: yes
  become_user: www-data
  args:
    chdir: /var/www/nextcloud

- name: Add trusted domain to config.php
  lineinfile:
    dest: /var/www/nextcloud/config/config.php
    line: "    1 => '{{ nextcloud_domain }}',"
    insertafter: "0 => '"

- name: Add local cache, urandom, and email to config.php
  lineinfile:
    dest: /var/www/nextcloud/config/config.php
    line: "{{ item }}"
    insertbefore: "\\);"
  with_items:
    - "  'memcache.local' => '\\OC\\Memcache\\APCu',"
    - "  'open_basedir' => '/dev/urandom',"
    - "  'mail_smtpmode' => 'sendmail',"
    - "  'mail_from_address' => 'admin',"
    - "  'mail_domain' => '{{ nextcloud_domain }}',"
    - "  'logfile' => '/var/log/nextcloud.log',"

# - name: Download additional Apps
#   git:
#     repo: "https://github.com/nextcloud/{{ item }}.git"
#     dest: "/var/www/nextcloud/apps/{{ item }}"
#     accept_hostkey: yes
#   with_items:
#     - twofactor_totp
#     - calendar
#     - contacts
#     - bookmarks
#     - tasks
#   become: true
#   become_user: www-data
#   notify: restart apache

- name: Enable extra Apps, disable usage survey
  command: php occ app:{{ item.state }} "{{ item.name }}"
  with_items:
  - { state: 'enable', name: 'admin_audit' }
  - { state: 'enable', name: 'external' }
  - { state: 'enable', name: 'files_accesscontrol' }
  - { state: 'enable', name: 'files_automatedtagging' }
  - { state: 'enable', name: 'files_external' }
#  - { state: 'enable', name: 'twofactor_totp' } # Disabled until update to 12.0
#  - { state: 'enable', name: 'calendar' }
#  - { state: 'enable', name: 'contacts' }
#  - { state: 'enable', name: 'bookmarks' }
#  - { state: 'enable', name: 'tasks' }
  - { state: 'disable', name: 'survey_client' }
  become: yes
  become_user: www-data
  ignore_errors: yes
  args:
    chdir: /var/www/nextcloud
  notify: restart apache
