- name: Install Logcheck and syslog-summary
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - logcheck
    - syslog-summary
  tags:
    - dependencies

- name: Configure logcheck
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=logcheck mode=0640
  with_items:
    - { src: 'etc_logcheck_logcheck.logfiles', dest: '/etc/logcheck/logcheck.logfiles' }
    - { src: 'etc_logcheck_logcheck.conf', dest: '/etc/logcheck/logcheck.conf' }

- name: Adjust Logcheck's cron
  copy: src=etc_cron.d_logcheck dest=/etc/cron.d/logcheck mode=0644
