- name: Install Logcheck
  apt: pkg=logcheck state=installed update_cache=yes
  tags:
    - dependencies

- name: Change logcheck to send mail to root
  lineinfile: dest=/etc/logcheck/logcheck.conf regexp=^SENDMAILTO line="SENDMAILTO=\"root\"" backup=yes state=present backrefs=yes
