- name: Add monitoring vhost to apache
  copy: src=etc_apache2_sites-available_00-status.conf dest=/etc/apache2/sites-available/00-status.conf

- name: Enable the status vhost
  command: a2ensite 00-status.conf creates=/etc/apache2/sites-enabled/00-status.conf
  notify: restart apache

- name: Install monit
  apt: pkg=monit state=installed
  tags:
    - dependencies

- name: Gather current PostgeSQL pid file
  shell: psql -tAc 'show external_pid_file'
  become: True
  become_user: postgres
  register: postgres_pid

- name: Copy monit master config file into place
  template: src=etc_monit_monitrc.j2 dest=/etc/monit/monitrc
  notify: restart monit

- name: Copy monit service config files into place
  copy: src=etc_monit_conf.d_{{ item }} dest=/etc/monit/conf.d/{{ item }}
  with_items:
    - apache2
    - clamav
    - cron
    - dovecot
    - fail2ban
    - pgsql
    - postfix
    - sshd
    - tomcat
    - znc
  notify: restart monit

- name: Copy monit service config files into place
  template: src=etc_monit_conf.d_pgsql.j2 dest=/etc/monit/conf.d/pgsql
  notify: restart monit

- name: Copy monit reduced rsyslog file into place
  copy: src=etc_rsyslog.d_30-monit.conf dest=/etc/rsyslog.d/30-monit.conf
  notify: restart rsyslog
