# Installs and configures apticron, unattended upgrades, and needrestart.
# Apticron will send an email when there are packages that need upgrading.
# Unattended upgrades will automatically run updates and upgrades on the system.
# The configuration files upgrade every package.  Needrestart will automatically
# restart programs that have been upgraded and is configured to do so.

- name: Install Apticron
  apt: pkg={{ item }} state=installed
  with_items:
    - apticron
    - needrestart
    - unattended-upgrades
  tags:
    - dependencies

- name: Apticron email configuration
  copy: src=etc_apticron_apticron.conf dest=/etc/apticron/apticron.conf

- name: Copy unattended upgrades settings in place
  copy: src={{ item.src }} dest={{ item.dest }} group=root owner=root
  with_items:
    - { src: 'etc_apt_apt.conf.d_20auto-upgrades', dest: '/etc/apt/apt.conf.d/20auto-upgrades' }
    - { src: 'etc_apt_apt.conf.d_50unattended-upgrades', dest: '/etc/apt/apt.conf.d/50unattended-upgrades' }

- name: Copy needrestart configuration file
  copy: src=etc_needrestart_conf.d_local.conf dest=/etc/needrestart/conf.d/local.conf
