---
- name: Install apticron
  apt: pkg={{ item }} state=installed
  with_items:
    - apticron
  tags:
    - dependencies

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf
