---
# Installs a encfs folder set for several other services

- name: Install encfs & fuse
  apt: pkg={{ item }} state=installed
  with_items:
    - encfs
    - fuse
    - libfuse-dev
  tags:
    - dependencies

- name: Create decrypted directory
  file: state=directory path=/decrypted group=mail mode=0775

- name: Create encrypted directory
  file: state=directory path=/encrypted

- name: Check if /encrypted directory is empty
  find: paths=/encrypted hidden=True
  register: encfs_check

- name: If /encrypted is empty, create the encfs there
  shell: printf "p\n{{ encfs_password }}" | encfs /encrypted /decrypted --public --stdinpass && touch /decrypted/lock
  when: encfs_check.matched == 0

- name: If /encrypted isn't empty and already mounted, mount it
  shell: printf "{{ encfs_password }}" | encfs /encrypted /decrypted --public --stdinpass
    creates="/decrypted/lock"
  when: encfs_check.matched != 0
