- name: Install fail2ban and xtables packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - fail2ban
    - python-inotifyx
    - xtables-addons-common
    - xtables-addons-dkms
    - libtext-csv-xs-perl
  tags:
    - dependencies

- name: get public IP
  ipify_facts:

- name: Copy fail2ban configuration into place
  template: src=etc_fail2ban_jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Copy fail2ban ssh re-ban configurations into place
  copy: src={{ item.src }} dest={{ item.dest }} group=root owner=root
  with_items:
  - { src: 'etc_fail2ban_filter.d_fail2ban-sshd.conf', dest: '/etc/fail2ban/filter.d/fail2ban-sshd.conf' }
  - { src: 'etc_fail2ban_jail.d_fail2ban-sshd.conf', dest: '/etc/fail2ban/jail.d/fail2ban-sshd.conf' }
  notify: restart fail2ban

- name: Create fail2ban daily cron report
  copy: src=etc_cron.daily_fail2ban dest=/etc/cron.daily/fail2ban mode=0755

- name: Copy xtables geoip weekly cron task
  copy: src=etc_cron.weekly_xtables dest=/etc/cron.weekly/xtables mode=0755

- name: Run initial download of geoip database
  command: /etc/cron.weekly/xtables creates=/usr/share/xt_geoip/ chdir=/usr/lib/xtables-addons/

- name: Ensure services are started
  service: name=fail2ban state=started enabled=yes
