# This will install and configure fail2ban.
# fail2ban uses the inotify backend if installed with it's backend= auto configuration.
# This also install a re-ban, where the fail2ban log is scanned and repeat
# offenders are banned for even longer.
# There is a daily cron report sent to the root user for monitoring.

- name: Install fail2ban package
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - fail2ban
    - python-inotifyx
  tags:
    - dependencies

- name: get public IP
  ipify_facts:

- name: Copy fail2ban configuration into place
  template: src=etc_fail2ban_jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Copy fail2ban ssh re-ban configurations into place
  copy: src={{ item.src }} dest={{ item.dest }} group=root owner=root
  with_items:
  - { src: 'etc_fail2ban_filter.d_fail2ban-sshd.conf', dest: '/etc/fail2ban/filter.d/fail2ban-sshd.conf' }
  - { src: 'etc_fail2ban_jail.d_fail2ban-sshd.conf', dest: '/etc/fail2ban/jail.d/fail2ban-sshd.conf' }
  notify: restart fail2ban

- name: Create fail2ban daily cron report
  copy: src=etc_cron.daily_fail2ban dest=/etc/cron.daily/fail2ban mode=0755

- name: Ensure services are started
  service: name=fail2ban state=started enabled=yes
