# This changes hostname, mailname, and hosts file to match that of the domain.
# The hosts file is without IPv6 as it's disabled system wide.

- name: Set hostname With hostname Command
  hostname:
    name: "{{ domain }}"
  notify:
    - restart systemd-hostnamed
    - restart systemd-logind

- name: Set mailname
  copy:
    content: "{{ domain }}\n"
    dest: /etc/mailname
    mode: 0644
    owner: root
    group: root

- name: Change hosts File
  template:
    src: etc_hosts
    dest: /etc/hosts
  notify:
    - restart systemd-hostnamed
    - restart systemd-logind

- name: Re-gather Facts
  action: setup
