---
# Changes hostname of systemd-logind

- name: Set Hostname with hostname command
  hostname:
    name: "{{ domain }}"
  notify:
    - restart systemd-hostnamed
    - restart systemd-logind

- name: Set mailname
  copy:
    content: "{{ domain }}\n"
    dest: /etc/mailname
    mode: 0644
    owner: root
    group: root

- name: Change hosts file with a backup
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1       {{ domain }} {{ domain | replace('.com', '') }}"
    state: present
    backup: yes
    backrefs: yes
  notify:
    - restart systemd-hostnamed
    - restart systemd-logind

- name: Re-gather facts
  action: setup
