---
# Changes hostname of systemd-logind

- name: Set Hostname with hostname command
  hostname:
    name: "{{ domain }}"
  notify:
    - restart systemd-hostnamed
    - restart systemd-logind

- name: Set mailname
  copy:
    content: "{{ domain }}\n"
    dest: /etc/mailname
    mode: 0644
    owner: root
    group: root

- name: Change hosts file
  template:
    src: etc_hosts
    dest: /etc/hosts
  notify:
    - restart systemd-hostnamed
    - restart systemd-logind

- name: Re-gather facts
  action: setup
