---

- include: hostname.yml
  tags: hostname
- include: timezone.yml
  tags: timezone
- include: encfs.yml
  tags: encfs
- include: users.yml
  tags: users
- include: apache.yml
  tags: apache
- include: apticron.yml
  tags: apticron
- include: ssl.yml
  tags: ssl
- include: letsencrypt.yml
  tags: letsencrypt
- include: ufw.yml
  tags: ufw
- include: security.yml
  tags: security
- include: ntp.yml
  tags: ntp
- include: google_auth.yml
  tags: google_auth
- include: postgres.yml
  tags: postgres
