# This installs several malware/rootkit/virus detection utilities.
# https://github.com/rfxn/linux-malware-detect/issues/28 is why a custom logrotate
# is needed.  All of these programs are configured to run daily or weekly, and
# to scan as much of the entire system as possible.

- name: Ensure repository key for Lynis is in place
  apt_key: url=http://packages.cisofy.com/keys/cisofy-software-public.key state=present
  tags:
    - dependencies

- name: Add Lynis repository
  apt_repository: repo="deb https://packages.cisofy.com/community/lynis/deb/ testing main"
  tags:
    - dependencies

# ed and inotify are needed for maldet
- name: Install malware detection packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - lynis
    - rkhunter
    - unhide
    - clamav-daemon
    - clamsmtp
    - inotify-tools
    - ed
  tags:
    - dependencies

- name: Download Linux Malware Detect Installer
  unarchive:
    src=http://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest=/root
    remote_src=yes

- name: Get Current Linux Malware Detect Version
  shell: "ls -d /root/maldetect*"
  register: lmd_version
  changed_when: false

- name: Install Linux Malware Detect
  shell: "{{ lmd_version.stdout }}/install.sh chdir={{ lmd_version.stdout }} creates=/usr/local/maldetect"

- name: Remove Malware Detect Installation files
  file: path={{ lmd_version.stdout }} state=absent

- name: Copy Linux Malware Detect Configuration
  template: src=usr_local_maldetect_conf.maldet dest=/usr/local/maldetect/conf.maldet
  notify: restart maldet

- name: Adjust Malware Detect's Ignored Paths
  copy: src=usr_local_maldetect_ignore_paths dest=/usr/local/maldetect/ignore_paths
  notify: restart maldet

- name: Add Root Directory to Malware Detect's Monitoring
  copy:
    content: "/\n"
    dest: /usr/local/maldetect/monitor_paths
    mode: 0644
  notify: restart maldet

- name: Install Malware Detect's Logrotate
  copy: src=etc_logrotate.d_maldet dest=/etc/logrotate.d/maldet

- name: Create Monthly Malware Detect Upgrade
  cron: name="LMD update" special_time=monthly job="maldet --update-ver"

- name: Copy rkhunter Configuration
  copy: src={{ item.src }} dest={{ item.dest }} group=root owner=root
  with_items:
  - { src: 'etc_default_rkhunter', dest: '/etc/default/rkhunter' }
  - { src: 'etc_rkhunter.conf.local', dest: '/etc/rkhunter.conf.local' }

- name: Create rkhunter's database of key system files
  command: rkhunter --propupd
    creates=/var/lib/rkhunter/db/rkhunter.dat

- name: Create Lynis Log Directory
  file: state=directory path=/var/log/lynis mode=0755

- name: Copy Lynis Weekly Cronjob Task
  template: src=etc_cron.weekly_lynis dest=/etc/cron.weekly/lynis mode=0755

- name: Copy ClamAV Configuration
  copy: src=etc_clamav_clamd.conf dest=/etc/clamav/clamd.conf mode=0644

- name: Copy Daily ClamAV Scan Task
  template: src=etc_cron.daily_clamav dest=/etc/cron.daily/clamav mode=0755

- name: Ensure Services Are Started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - clamav-daemon
    - clamav-freshclam
    - clamsmtp
    - maldet
