- name: Ensure repository key for Lynis is in place
  apt_key: url=http://packages.cisofy.com/keys/cisofy-software-public.key state=present
  tags:
    - dependencies

- name: Add Lynis repository
  apt_repository: repo="deb https://packages.cisofy.com/community/lynis/deb/ {{ ansible_distribution_release }} main"
  tags:
    - dependencies

- name: Install malware detection packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - lynis
    - rkhunter
    - unhide
    - clamav-daemon
    - inotify-tools
  tags:
    - dependencies

- name: Download Linux Malware Detect installer
  unarchive:
    src=http://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest=/root
    remote_src=yes

- name: Install Linux Malware Detect
  shell: /root/maldetect-1.6/install.sh chdir=/root/maldetect-1.6/ creates=/usr/local/maldetect

- name: Change Linux Malware Detect configuration
  lineinfile: dest=/usr/local/maldetect/conf.maldet regexp="{{ item.regexp }}" line="{{ item.line}}" backup=yes state=present backrefs=yes
  with_items:
    - { regexp: ^email_alert, line: "email_alert=\"1\"" }
    - { regexp: ^email_addr, line: "email_addr=\"root\"" }
    - { regexp: ^# default_monitor_mode=\"users\", line: "default_monitor_mode=\"users\"" }

- name: Copy rkhunter configurations into place
  copy: src={{ item.src }} dest={{ item.dest }} group=root owner=root
  with_items:
  - { src: 'etc_default_rkhunter', dest: '/etc/default/rkhunter' }
  - { src: 'etc_rkhunter.conf', dest: '/etc/rkhunter.conf' }

- name: Create rkhunter's database of key system files
  command: rkhunter --propupd
    creates=/var/lib/rkhunter/db/rkhunter.dat

- name: Create Lynis log directory
  file: state=directory path=/var/log/lynis mode=0755

- name: Copy Lynis weekly cronjob task
  template: src=etc_cron.weekly_lynis dest=/etc/cron.weekly/lynis mode=0755

- name: Copy Daily ClamAV scan task
  template: src=etc_cron.daily_clamav dest=/etc/cron.daily/clamav mode=0755

- name: Ensure services are started
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - clamav-daemon
    - clamav-freshclam
    - maldet
  ignore_errors: yes
