# Defines tasks applicable for NTP (Network Time Protocol).  The default
# configuration works well.

- name: Install ntp
  apt: pkg=ntp state=installed
  tags:
    - dependencies

- name: Ensure ntpd is running
  service: name=ntp state=started enabled=yes
