---
# Defines tasks applicable for postgreSQL

- name: Install Postgres
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql
    - python-psycopg2
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes

- name: Gather current PostgeSQL data directory
  shell: ps aux | grep postgres | grep -- -D | awk '{print $13}'
  register: postgres_data

- name: Stop PostgreSQL to change data directory location
  service: name=postgresql state=stopped

- name: Move PostgreSQL database
  command: mv "{{ postgres_data.stdout_lines | first }}" /decrypted/postgres
    creates=/decrypted/postgres

- name: Link new folder to original location
  file: src=/decrypted/postgres dest="{{ postgres_data.stdout_lines | first }}" state=link

- name: Restart PostgreSQL
  service: name=postgresql state=started
