---
# Install and configure packages related to security.  SSH and SSHD are
# hardened, apparmor is installed, and umask is changed to be more secure.

- name: Install Security Related Packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - apparmor
    - apparmor-profiles
    - apparmor-profiles-extra
    - apparmor-utils
  tags:
    - dependencies

- name: Update sshd For More Secure Defaults
  template: src=etc_ssh_sshd_local.j2 dest=/etc/ssh/sshd_local
  notify: restart ssh

- name: Configure SSHD To Use Custom Config
  lineinfile: dest=/etc/default/ssh regexp=^SSHD_OPTS line="SSHD_OPTS=-f /etc/ssh/sshd_local" backup=yes state=present backrefs=yes
  notify: restart ssh

- name: Update ssh For More Secure Defaults
  template: src=etc_ssh_ssh_config.j2 dest=/etc/ssh/ssh_config

- name: Adjust Login Password Defaults And umask
  lineinfile: dest=/etc/login.defs regexp="{{ item.regexp }}" line="{{ item.line}}" backup=yes state=present backrefs=yes
  with_items:
    - { regexp: ^UMASK, line: "UMASK   027" }
    - { regexp: ^PASS_MIN_DAYS, line: "PASS_MIN_DAYS 1" }
    - { regexp: ^PASS_MAX_DAYS, line: "PASS_MAX_DAYS 980" }
    - { regexp: ^PASS_WARN_AGE, line: "PASS_WARN_AGE 21" }

- name: Adjust init.d/rc umask
  lineinfile: dest=/etc/init.d/rc regexp=^umask line="umask 027" backup=yes state=present backrefs=yes
