# This task installs many commonly used packages, upgrades the system,
# and makes sure the UTF-8 local is available.

- name: Install commonly used software packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - acl
    - aptitude
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - cmake
    - debian-goodies
    - debian-keyring
    - debsums
    - dnsutils
    - git
    - grc
    - haveged
    - htop
    - iftop
    - inxi
    - intel-microcode
    - inxi
    - iotop
    - kbd
    - libpq-dev
    - lm-sensors
    - mcelog
    - molly-guard
    - mosh
    - most
    - mtr
    - p7zip-full
    - p7zip-rar
    - python-dev
    - python3-dev
    - rng-tools
    - ruby-full
    - silversearcher-ag
    - software-properties-common
    - smartmontools
    - sudo
    - sysstat
    - traceroute
    - vim-nox
    - wget
    - zip
    - unrar
    - unzip
  tags:
    - dependencies

- name: Upgrade all packages
  apt: upgrade=dist
  tags:
    - dependencies

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present
