---
# This file will change certain common system variables

- name: Turn off ipv6
  sysctl: name="{{ item }}" value=1 sysctl_set=yes reload=yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

# https://en.wikipedia.org/wiki/Syslog
# console_loglevel, default_message_loglevel, minimum_console_loglevel, default_console_loglevel
- name: Reduce console noise
  sysctl:
    name: kernel.printk
    value: 3 4 1 3
    sysctl_set: yes
    reload: yes

- name: Increase max open folders for IMAP IDLE connections
  sysctl:
    name: fs.inotify.max_user_instances
    value: 1024
    sysctl_set: yes
    reload: yes

- name: Increase max watched files for maldet
  sysctl:
    name: fs.inotify.max_user_watches
    value: 262144
    sysctl_set: yes
    reload: yes

- name: Initilaize random number generator with seeds
  command: dd if=/dev/random of=/dev/urandom bs=1 count=32

- name: Enable primary drive fstab filesystem check on every boot
  shell: tune2fs -c 1 $(blkid | cut -d":" -f1)
