---
# This file will change certain common system variables

- name: Turn off ipv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    reload: yes

- name: Reduce console noise
  sysctl:
    name: kernel.printk
    value: 3 4 1 3
    sysctl_set: yes
    reload: yes

- name: Increase max open folders for IMAP IDLE connections
  sysctl:
    name: fs.inotify.max_user_instances
    value: 1024
    sysctl_set: yes
    reload: yes
