---
# This file will change certain common system variables.
# The random number generator is seeded as most cloud systems lack initial entropy.
# fsck is configured to run on every boot.
# machine-id is recreated because it might not match the dbus machine-id on a
# cloud instance.
# Ensures that journald can function

- name: Copy Custom Kernel Configuration
  copy:
    src: etc_sysctl.d_local.conf
    dest: /etc/sysctl.d/local.conf

- name: Reload Kernel Variables
  sysctl:
    reload: yes

- name: Copy Local Security Limits
  copy:
    src: etc_security_limits.d_local.conf
    dest: /etc/security/limits.d/local.conf

- name: Initialize Random Number Generator With Seeds
  command: "dd if=/dev/random of=/dev/urandom bs=1 count=32"

- name: Enable Primary Drive fstab Filesystem Check On Every Boot
  shell: 'tune2fs -c 1 $(findmnt -n -o source /)'

# - name: Remove Existing systemd machine-id
#   file:
#     path: /etc/machine-id
#     state: absent
#   notify:
#     - restart journald
#     - restart tmpfiles
# 
# - name: Recreate machine-id
#   command: systemd-machine-id-setup
#   notify:
#     - restart journald
#     - restart tmpfiles

- name: Confirm journald Has Logging Directory
  file:
    path: /var/log/journal
    state: directory
  notify:
    - restart journald
    - restart tmpfiles

- name: Ensure Correct Permissions On journald Directory
  command: systemd-tmpfiles --create --prefix /var/log/journal
  notify:
    - restart journald
    - restart tmpfiles
