- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

- name: restart solr
  service:
    name: tomcat8
    state: restarted

- name: import sql postfix
  action: shell PGPASSWORD='{{ mail_db_password }}' psql -h 127.0.0.1 -d {{ mail_db_database }} -U {{ mail_db_username }} -f /etc/postfix/import.sql --set ON_ERROR_STOP=1
  notify: restart postfix

- name: restart opendmarc
  service:
    name: opendmarc
    state: restarted

- name: restart rspamd
  service:
    name: rspamd
    state: restarted

- name: restart redis-server
  service:
    name: redis-server
    state: restarted

- name: restart rmilter
  service:
    name: rmilter
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
