- name: restart monit
  service:
    name: monit
    state: restarted

- name: restart collectd
  service:
    name: collectd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
